---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kubecit-service
  namespace: wlb965
spec:
  filterTags:
    extract: $ts
    pattern: ^(?P<ts>[0-9]+)-[a-z0-9]+
  imageRepositoryRef:
    name: kubecit-service
  policy:
    numerical:
      order: asc
